version: "3"

services:
  # admin:
  #   build:
  #     context: ./admin
  #   ports:
  #     - 3001:80

  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - 80:80

  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./:/code

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - mongodb:/data/db

# volumes:
#   mongodb:
